### ISSUE TITLE
MOcov gets confused with "comments"

### ISSUE THREAD

**Issue by Remi-Gau** [MOxUnit/MOcov#19]
I have been getting a "strange" error (most likely user induced) I suspect but I thought I would report it: for the record.

Similarly I have been getting this with travis CI and not locall which makes me think this is a MOcov issue and not a MOxUnit one.

I was getting this series of fail of the CI: 
https://travis-ci.com/github/cpp-lln-lab/CPP_BIDS_SPM_pipeline/jobs/402478171

See for example line 1417:
```
failure: parse error near line 95 of file /tmp/oct-hyiVh2/utils/checkOptions.m

  syntax error

>>> mocov_line_covered(51,'utils/checkOptions.m',95,1);                                      'Contrasts', struct( ...
```

This was fixed by this commit: https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline/pull/120/commits/4570441039379944b8c9eb2d2e98551e8a4cdf60

That pretty much turns a "comment" like this:
```matlab
Steps = struct( ...
    fieldsToSet.result.Steps = struct( ...
                                      'Level',  '', ... dataset, run, subject
                                      'Contrasts' , [ ] )
```
into a proper comment:
```matlab
Steps = struct( ...
    fieldsToSet.result.Steps = struct( ...
                                      'Level',  '', ...  % dataset, run, subject
                                      'Contrasts' , [ ] )
```

Seems that this messes up with the parsing to measure code coverage (or at least this is my noob interpretation).

Note sure if this is a known "issue".

**Comment by nno** [comment]
@Remi-Gau thanks for the report.

I was not aware that such line continuations are allowed, but indeed I now see that this is valid code. Will see if this can be fixed easily.

**Comment by nno** [comment]
@Remi-Gau can you see and try if PR #20 addresses the issue?

**Comment by Remi-Gau** [comment]
will try to make that run locally.

it's been a while since I did not delegate that to "the cloud". :-)

**Comment by Remi-Gau** [comment]
VERY silly question: there is no need to re-run Make before I run this PR. I can just checkout a different branch.
