### ISSUE TITLE
Add option to exclude individual files

### ISSUE THREAD

**Issue by scottclowe** [MOxUnit/MOcov#4]
I would like to test the coverage over a (recursive) folder, but exclude individual files within the folder(s).

This would be a useful feature generally if you have `.m` files which don't need to be in the coverage report but which should be in the folder with the rest of the package contents.

However, in my use-case I specifically want to exclude a file which is used to determine the path to the package (for the purpose of loading resource files within the package). This file needs to be excluded because the path will be incorrect if it is moved to a temporary directory for coverage calculation purposes.

**Comment by nno** [comment]
Probably the easiest way to achieve this is:
- update mocov_find_files.m to support an exclusion option, for example as a fourth argument. This could be a cell with filenames and/or wildecard patterns.
- add an option to mocov.m which specifies a file (possibly pattern) to be excluded. Even better if multiple exclusion options can be specified.
- the excluded files are passed to the MOcovMFileCollection/MOcovMFileColleciton.m constructor and stored internally
- In MOcovMFileCollection/prepare.m, pass the excluded files to mocov_find_files.m

Do you think this will address your use-case?

**Comment by scottclowe** [comment]
Yes, this sounds like it would be a good solution for this issue and would work for me.

However for my particular use-case, closing #5 would let me check the coverage on the file in question instead of omitting it from the coverage dataset.
