### ISSUE TITLE
Error when using MOcov with test subject coded as a class

### ISSUE THREAD

**Issue by abravalheri** [MOxUnit/MOcov#8]
On Ubuntu Trusty (32 bits - i686-pc-linux-gnu) with GNU Octave 4.0.2, running tests for subjects that use the "new" class definition syntax results in the following error:

```bash
failure: parse error near line 1 of file /tmp/oct-QJBT47/AClass.m

  syntax error

>>> mocov_line_covered(1,'AClass.m',1,1);classdef AClass < handle
                                                ^

  test_AClass>test_one:6 (/home/vagrant/drafts/dummy-mocov-example-for-issue/tests/test_AClass.m)

--------------------------------------------------

FAILED (failure=1)
ans = 0
```

Is there any place where the supported syntax is described?

The minimal code in the repository https://github.com/abravalheri/dummy-mocov-example-for-issue/ can be used to reproduce the error.

Note that when MOcov is disabled the test suite runs normally.

```bash
suite: 1 tests
hello world!.
--------------------------------------------------

OK
ans =  1
```

Thank you in advance! (Also thanks for working in a such unique and necessary project)

**Comment by nno** [comment]
@abravalheri it seems that PR #9 (now merged) has addressed this issue, so I will close this issue now. If PR #9 did not address it, please re-open this issue and explain what else needs to be done.
